# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: region.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'region.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregion.proto\x12\x0e\x64ssd.region.v1\"F\n\nAgentState\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\"[\n\x0eHandOffRequest\x12\x10\n\x08shard_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x04\x12)\n\x05\x61gent\x18\x03 \x01(\x0b\x32\x1a.dssd.region.v1.AgentState\"3\n\x0fHandOffResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2Y\n\x0bRegionOwner\x12J\n\x07HandOff\x12\x1e.dssd.region.v1.HandOffRequest\x1a\x1f.dssd.region.v1.HandOffResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'region_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTSTATE']._serialized_start=32
  _globals['_AGENTSTATE']._serialized_end=102
  _globals['_HANDOFFREQUEST']._serialized_start=104
  _globals['_HANDOFFREQUEST']._serialized_end=195
  _globals['_HANDOFFRESPONSE']._serialized_start=197
  _globals['_HANDOFFRESPONSE']._serialized_end=248
  _globals['_REGIONOWNER']._serialized_start=250
  _globals['_REGIONOWNER']._serialized_end=339
# @@protoc_insertion_point(module_scope)
