# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import spine_pb2 as spine__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in spine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MembershipStub:
    """Membership: read-only view of the cluster as this node's SWIM sees it.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMembers = channel.unary_unary(
                '/dssd.spine.v1.Membership/GetMembers',
                request_serializer=spine__pb2.GetMembersRequest.SerializeToString,
                response_deserializer=spine__pb2.GetMembersResponse.FromString,
                _registered_method=True)


class MembershipServicer:
    """Membership: read-only view of the cluster as this node's SWIM sees it.
    """

    def GetMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MembershipServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMembers,
                    request_deserializer=spine__pb2.GetMembersRequest.FromString,
                    response_serializer=spine__pb2.GetMembersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dssd.spine.v1.Membership', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dssd.spine.v1.Membership', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Membership:
    """Membership: read-only view of the cluster as this node's SWIM sees it.
    """

    @staticmethod
    def GetMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.spine.v1.Membership/GetMembers',
            spine__pb2.GetMembersRequest.SerializeToString,
            spine__pb2.GetMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RaftStub:
    """Raft: the two RPCs from the Raft paper (Figure 2). One node can host
    several independent Raft groups (one per shard); `group` says which.
    The DiLoCo workers use a single group named "".
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/dssd.spine.v1.Raft/RequestVote',
                request_serializer=spine__pb2.RequestVoteArgs.SerializeToString,
                response_deserializer=spine__pb2.RequestVoteReply.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/dssd.spine.v1.Raft/AppendEntries',
                request_serializer=spine__pb2.AppendEntriesArgs.SerializeToString,
                response_deserializer=spine__pb2.AppendEntriesReply.FromString,
                _registered_method=True)


class RaftServicer:
    """Raft: the two RPCs from the Raft paper (Figure 2). One node can host
    several independent Raft groups (one per shard); `group` says which.
    The DiLoCo workers use a single group named "".
    """

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=spine__pb2.RequestVoteArgs.FromString,
                    response_serializer=spine__pb2.RequestVoteReply.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=spine__pb2.AppendEntriesArgs.FromString,
                    response_serializer=spine__pb2.AppendEntriesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dssd.spine.v1.Raft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dssd.spine.v1.Raft', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Raft:
    """Raft: the two RPCs from the Raft paper (Figure 2). One node can host
    several independent Raft groups (one per shard); `group` says which.
    The DiLoCo workers use a single group named "".
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.spine.v1.Raft/RequestVote',
            spine__pb2.RequestVoteArgs.SerializeToString,
            spine__pb2.RequestVoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.spine.v1.Raft/AppendEntries',
            spine__pb2.AppendEntriesArgs.SerializeToString,
            spine__pb2.AppendEntriesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
