# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import trainer_pb2 as trainer__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerStub:
    """Every worker serves Trainer. Sync is only answered by the current Raft
    leader: workers submit their pseudo-gradient and block until the round
    closes, then all receive the new global model together. Status lets
    the experiment script read each worker's progress.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sync = channel.unary_unary(
                '/dssd.trainer.v1.Trainer/Sync',
                request_serializer=trainer__pb2.SyncRequest.SerializeToString,
                response_deserializer=trainer__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/dssd.trainer.v1.Trainer/Status',
                request_serializer=trainer__pb2.StatusRequest.SerializeToString,
                response_deserializer=trainer__pb2.StatusResponse.FromString,
                _registered_method=True)


class TrainerServicer:
    """Every worker serves Trainer. Sync is only answered by the current Raft
    leader: workers submit their pseudo-gradient and block until the round
    closes, then all receive the new global model together. Status lets
    the experiment script read each worker's progress.
    """

    def Sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sync': grpc.unary_unary_rpc_method_handler(
                    servicer.Sync,
                    request_deserializer=trainer__pb2.SyncRequest.FromString,
                    response_serializer=trainer__pb2.SyncResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=trainer__pb2.StatusRequest.FromString,
                    response_serializer=trainer__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dssd.trainer.v1.Trainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dssd.trainer.v1.Trainer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Trainer:
    """Every worker serves Trainer. Sync is only answered by the current Raft
    leader: workers submit their pseudo-gradient and block until the round
    closes, then all receive the new global model together. Status lets
    the experiment script read each worker's progress.
    """

    @staticmethod
    def Sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.trainer.v1.Trainer/Sync',
            trainer__pb2.SyncRequest.SerializeToString,
            trainer__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.trainer.v1.Trainer/Status',
            trainer__pb2.StatusRequest.SerializeToString,
            trainer__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
